# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master



stages:
- stage: A
  jobs:
  - job: A1
    pool:
      vmImage: 'ubuntu-latest'
      steps:
      - script: |
          echo sleep 40

  - job: A2
    pool:
      vmImage: 'ubuntu-latest'
      steps:
      - script: |
          echo sleep 20

- stage: B
  jobs:
  - job: B1
    pool:
      vmImage: 'ubuntu-latest'
      steps:
      - script: |
          echo sleep 5
  - job: B2
    pool:
      vmImage: 'ubuntu-latest'
      steps:
      - script: |
          exit 1